# Generated by Django 3.0.2 on 2020-01-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_item_prop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='prop',
            new_name='owner',
        ),
    ]
